// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Y4iXjQG1bZ3Or0HBghS5BGBmH1Ma160',
    appId: '1:454504804512:web:aad6d4d2b74b1f62bd19c5',
    messagingSenderId: '454504804512',
    projectId: 'safe-voice-app',
    authDomain: 'safe-voice-app.firebaseapp.com',
    storageBucket: 'safe-voice-app.firebasestorage.app',
    measurementId: 'G-M5MGMYD8F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsTJOL0paupQLGurv3CxAyd-w2csv_N8M',
    appId: '1:454504804512:android:9425edc8423e96efbd19c5',
    messagingSenderId: '454504804512',
    projectId: 'safe-voice-app',
    storageBucket: 'safe-voice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfLZicttuSHFS4s7jBM3tsQDGe2O67gsQ',
    appId: '1:454504804512:ios:0d008e993594c0d8bd19c5',
    messagingSenderId: '454504804512',
    projectId: 'safe-voice-app',
    storageBucket: 'safe-voice-app.firebasestorage.app',
    iosBundleId: 'com.example.safeVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfLZicttuSHFS4s7jBM3tsQDGe2O67gsQ',
    appId: '1:454504804512:ios:0d008e993594c0d8bd19c5',
    messagingSenderId: '454504804512',
    projectId: 'safe-voice-app',
    storageBucket: 'safe-voice-app.firebasestorage.app',
    iosBundleId: 'com.example.safeVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Y4iXjQG1bZ3Or0HBghS5BGBmH1Ma160',
    appId: '1:454504804512:web:1f30d8632b048d78bd19c5',
    messagingSenderId: '454504804512',
    projectId: 'safe-voice-app',
    authDomain: 'safe-voice-app.firebaseapp.com',
    storageBucket: 'safe-voice-app.firebasestorage.app',
    measurementId: 'G-8HG3XHZH5R',
  );
}
